### ISSUE TITLE
Improve the UI of website!

### ISSUE THREAD

**Issue by sudipt1999** [sudipt1999/EDM-Mimic#1]
Kindly update the UI as per your creativity !

**Comment by iamshm** [comment]
I would like to work on this

**Comment by sudipt1999** [comment]
Sure ! Go ahead

**Comment by iamshm** [comment]
Already completed! Check the PR section 💯

**Comment by iamshm** [comment]
I have already made a website.
Check your PR

**Comment by sudipt1999** [comment]
Thanks  for the contribution ! Merged ! Closing the issue !
